# Generated by Django 5.0.1 on 2024-02-08 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('feedback_receive', models.CharField(max_length=255)),
                ('feedback_reply', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('feedback_date', models.DateTimeField()),
                ('customer', models.ForeignKey(limit_choices_to={'username__startswith': 'cst'}, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, default=None, limit_choices_to={'username__startswith': 'mgr'}, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
