# Generated by Django 5.0.1 on 2024-02-08 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'username__startswith': 'cst'}, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_feedbacks', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'username__startswith': 'mgr'}, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
