# Generated by Django 5.0.1 on 2024-02-11 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproduct', '0005_rename_productid_product_product_id_and_more'),
        ('app', '0006_alter_feedback_customer_alter_feedback_manager'),
        ('viewproducts', '0004_alter_cart_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_qty', models.IntegerField()),
                ('order_amt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.TextField()),
                ('delivery_addr', models.TextField()),
                ('delivery_remark', models.TextField(blank=True, default=None, null=True)),
                ('cart', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.RESTRICT, to='viewproducts.cart')),
                ('customer', models.ForeignKey(limit_choices_to={'username__startswith': 'cst'}, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_orders', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('staff', models.ForeignKey(limit_choices_to={'username__startswith': 'sstf'}, on_delete=django.db.models.deletion.RESTRICT, related_name='staff_orders', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderItem_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('orderUnitPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orderItem_qty', models.IntegerField()),
                ('orderItem_subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(limit_choices_to={'username__startswith': 'cst'}, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_orderitems', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('order', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.RESTRICT, to='app.order')),
                ('product', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.RESTRICT, to='addproduct.product')),
            ],
        ),
    ]
