# Generated by Django 4.2.9 on 2024-02-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPic',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
