# Generated by Django 5.0.1 on 2024-02-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addproduct', '0004_alter_product_productpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productID',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productInfo',
            new_name='product_info',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productPic',
            new_name='product_pic',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productPrice',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productQty',
            new_name='product_qty',
        ),
    ]
