# Generated by Django 5.0.1 on 2024-02-09 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addproduct', '0005_rename_productid_product_product_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cart_amt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cart_qty', models.IntegerField()),
                ('customer', models.ForeignKey(limit_choices_to={'username__startswith': 'cst'}, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_orders', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cartItem_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cartItem_qty', models.IntegerField()),
                ('cartUnitPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cartItem_subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cart_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.RESTRICT, to='viewproducts.cart')),
                ('product', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.RESTRICT, to='addproduct.product')),
            ],
        ),
    ]
