# Generated by Django 5.0.1 on 2024-02-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewproducts', '0002_alter_cartitem_cart_id_alter_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
