# Generated by Django 5.0.1 on 2024-02-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewunassignedorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnassignedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
