# Generated by Django 4.1.4 on 2024-02-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewunassignedorder', '0004_assigneddeliveryorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedDeliveryOrder',
        ),
    ]
