# Generated by Django 5.0.1 on 2024-02-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewunassignedorder', '0005_delete_assigneddeliveryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='unassigneddeliveryorder',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
