# Generated by Django 5.0.1 on 2024-02-11 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewunassignedorder', '0006_unassigneddeliveryorder_delivery_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_pic',
            field=models.ImageField(blank=True, null=True, upload_to='proof_photo/'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Unassigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='UnassignedDeliveryOrder',
        ),
    ]
