# Generated by Django 5.0.1 on 2024-02-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewunassignedorder', '0008_remove_deliveryorder_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery_id',
            field=models.CharField(max_length=10),
        ),
    ]
